# Generated by Django 3.0 on 2023-02-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('birthdate', models.DateField()),
                ('gender', models.TextField(max_length=8)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('is_delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('topic', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
